library(shiny)
library(digest)
library(twitteR)
options(java.parameters = "- Xmx2048m")
options(digits = 12)
library(twitteR)
library(qdap)
library(qdapDictionaries)
library(qdapRegex)
library(qdapTools)
library(rJava)
library(NLP)
library(openNLP)
library(tm)
library(stringr)
library(gsubfn)
library(plyr)
library(dplyr)
library(openNLPmodels.en)
library(openNLPdata)
library(data.table)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(RMySQL)
library(DBI)
library(textclean)
library(textreg)
library(digest)

# set the number of failed attempts allowed before user is locked out

num_fails_to_lockout <- 3
con <- dbConnect(MySQL(), host="localhost", dbname="twitter", user="root", password="shubham95")
print("Connection Established")
dbSendQuery(con,"Truncate table Original_Tweets")
print("Table Deleted")
dbSendQuery(con,"Truncate table prior_values_noun")
print("Table Deleted")
dbSendQuery(con,"Truncate table prior_values_verb")
print("Table Deleted")
dbSendQuery(con,"Truncate table tweets")
print("Table Deleted")

fn <- "nounfile.csv"
if (file.exists(fn)) file.remove(fn)
print("File Deleted")

fn <- "verbfile.csv"
if (file.exists(fn)) file.remove(fn)
print("File Deleted")