library(shiny)
library(digest)
library(twitteR)
options(java.parameters = "- Xmx2048m")
options(digits = 12)
library(twitteR)
library(qdap)
library(qdapDictionaries)
library(qdapRegex)
library(qdapTools)
library(rJava)
library(NLP)
library(openNLP)
library(tm)
library(stringr)
library(gsubfn)
library(plyr)
library(dplyr)
library(openNLPmodels.en)
library(openNLPdata)
library(data.table)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(RMySQL)
library(DBI)
library(textclean)
library(textreg)
library(digest)

# set the number of failed attempts allowed before user is locked out

num_fails_to_lockout <- 3